### ISSUE TITLE
Boot will not work from behind proxy

### ISSUE THREAD

**Issue by sebukoleth** [boot-clj/boot-bin#2]
The 'download' method directly uses URL.openStream without setting proxy. There are two options
(i)  try setting system property java.net.useSystemProxies=true before URL.openStream()
(ii) let boot.exe/boot.sh accept proxyHost, proxyPort, proxyUserName and proxyPassword. Then use standard Java system properties to set these into the JVM

**Comment by gphilipp** [comment]
I'm behind a corporate proxy which requires authentication so I have the same issue.
And also, I'm using windows :cry: 

The problem I see is two-fold. 

1. It seems like the boot.exe binary will not honor the BOOT_JVM_OPTIONS as it's only read in [head.sh](https://github.com/boot-clj/boot-bin/blob/91e30129ae4485df2185d7539ba1beef33440777/src/head.sh) which is concatenaned at the top of the boot.sh script (there's no `boot.bat` or `boot.cmd` equivalent)
2. Even if it could read the BOOT_JVM_OPTIONS, you'd have to set additional proxyUsername and proxyPassword since they don't exist for the JVM, and configure a default Authenticator.

```cmd
D:\gphilip\dev>boot
Downloading https://github.com/boot-clj/boot/releases/download/2.4.2/boot.jar...
Exception in thread "main" java.net.UnknownHostException: github.com
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
        at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
        at sun.net.NetworkClient.doConnect(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at java.net.URL.openStream(Unknown Source)
        at Boot.download(Boot.java:173)
        at Boot.install(Boot.java:224)
        at Boot.main(Boot.java:243)
```

**Comment by micha** [comment]
@sebukoleth @gphilipp Sorry for the loooooong delay, this one somehow slipped by unnoticed :(

I believe you can set JVM options in a `boot.l4j.ini` file, as described [here][0]. One thing the launch4j documentation doesn't make clear is that the `boot.l4j.ini` file must be in the same directory as `boot.exe`.

[0]: http://launch4j.sourceforge.net/docs.html#Additional_jvm_options

**Comment by HakimCassimallyBBC** [comment]
This is also an issue on Mac/Linux (e.g. the Windows solution as above won't work for us.)  It looks like `boot` doesn't actually use the BOOT_JVM_OPTIONS described from the boot.properties, and we've not yet had any success setting these in the environment either.

Any suggestions or solutions gratefully received - we're currently working around this issue by changing our wifi endpoint to avoid the proxy entirely, which is not ideal.

**Comment by alandipert** [comment]
Have you tried configuring with the `:proxy` keyword argument to `set-env!`? https://github.com/boot-clj/boot/wiki/Boot-Environment

I think you might be successfully setting these variables, but Pomegranate/Aether (libraries we use that do Maven stuff) aren't taking them into account.

**Comment by micha** [comment]
@HakimCassimallyBBC Alternatively, have you tried something like this?

```bash
BOOT_JVM_OPTIONS='-Dhttps.proxyHost=1.2.3.4' boot ...
```

See http://docs.oracle.com/javase/7/docs/technotes/guides/net/proxies.html

**Comment by HakimCassimallyBBC** [comment]
Thanks @micha @alandipert.  I thought we'd tried the BOOT_JVM_OPTIONS, but perhaps we only did that in boot.properties as we assumed that was equivalent to setting on command-line.  Will give those options a go next time I change back to the other proxied network!

**Comment by sharmp07** [comment]
Thanks @HakimCassimallyBBC, worked for me.

**Comment by MerelyAPseudonym** [comment]
@micha the `boot.l4j.ini` trick you [mentioned above](https://github.com/boot-clj/boot-bin/issues/2#issuecomment-259479730) worked for me on a Windows 7 machine. (I thought you might appreciate another data point.)

Also, the `boot.l4j.ini` file seems to be necessary only when bootstrapping; I can delete `boot.l4j.ini` but still download new dependencies from a fresh REPL. I suspect that my `http_proxy` and `https_proxy` environment variables are being used by that point.

**Comment by raszi** [comment]
I verified, providing `https.proxyHost` and `https.proxyPort` in `BOOT_JVM_OPTIONS` is working.

**Comment by flyboarder** [comment]
Issue moved to boot-clj/boot#674
